package com.comp2042.event;

/**
 * Enumeration representing the source of a game event.
 * Distinguishes between user-initiated actions and system-generated events.
 */
public enum EventSource {
    /** Event initiated by user input */
    USER, 
    /** Event generated by the game thread (automatic brick falling) */
    THREAD
}

